### ISSUE TITLE
error when creating a new radar chart

### ISSUE THREAD

**Issue by scampi** [sirensolutions/kibi_radar_vis#3]
tested with kibana 4.3

```
TypeError: Cannot read property 'displayName' of undefined
    at http://localhost:5601/bundles/kibana.bundle.js:110314:56
    at Array.forEach (native)
    at http://localhost:5601/bundles/kibana.bundle.js:110308:21
    at Array.forEach (native)
    at Scope.$scope.processTableGroups (http://localhost:5601/bundles/kibana.bundle.js:110305:27)
    at Object.fn (http://localhost:5601/bundles/kibana.bundle.js:110333:21)
    at Scope.$digest (http://localhost:5601/bundles/commons.bundle.js:43427:30)
    at Scope.$apply (http://localhost:5601/bundles/commons.bundle.js:43698:25)
    at done (http://localhost:5601/bundles/commons.bundle.js:38147:48)
    at completeRequest (http://localhost:5601/bundles/commons.bundle.js:38345:8)
```

**Comment by fhisashi** [comment]
Any response on this ? I'm getting the same error

**Comment by scampi** [comment]
The visualization needs to be updated to work with kibana 4.4.1 (Kibi is synced with that version). Other tasks blocked this. Feel free to submit a PR if you want ;o)

**Comment by scampi** [comment]
I just tried with kibana 4.4.3 and I got no issue. @fhisashi Could you try that newer version of kibana and see if you still have that problem ?

**Comment by Feaisil** [comment]
It seems the same error occurs with kibana 4.5.1 (Or I did something wrong... ;) ):

commons.bundle.js?v=9892:39571 TypeError: Cannot read property 'displayName' of undefined
    at http://127.0.0.1:8080/bundles/kibana.bundle.js?v=9892:114972:56
    at Array.forEach (native)
    at http://127.0.0.1:8080/bundles/kibana.bundle.js?v=9892:114966:21
    at Array.forEach (native)
    at Scope.$scope.processTableGroups (http://127.0.0.1:8080/bundles/kibana.bundle.js?v=9892:114963:27)
    at Object.fn (http://127.0.0.1:8080/bundles/kibana.bundle.js?v=9892:114991:21)
    at Scope.$digest (http://127.0.0.1:8080/bundles/commons.bundle.js?v=9892:42920:30)
    at Scope.$apply (http://127.0.0.1:8080/bundles/commons.bundle.js?v=9892:43191:25)
    at done (http://127.0.0.1:8080/bundles/commons.bundle.js?v=9892:37640:48)
    at completeRequest (http://127.0.0.1:8080/bundles/commons.bundle.js?v=9892:37838:8)

**Comment by scampi** [comment]
I didn't test with 4.5.1. For now use this visualization with 4.4.3.
This will be ported to 4.5.1 with the next release of kibi

**Comment by szydan** [comment]
similar to https://github.com/sirensolutions/kibi_radar_vis/issues/7

**Comment by szydan** [comment]
Fixed by https://github.com/sirensolutions/kibi_radar_vis/pull/11
